### PR TITLE
Bump pybind11 and version

### PR DESCRIPTION
**Pull request by vlarsson**
Bumps the pybind11 version to the latest. There seem to be some segfault issues that are resolved in this version. Also bump the version number to 2.0.4.

@pablospe @Parskatt it would be good to push new version to pypi as this should hopefully fix some of the crashes.

I've also added a flag to disable -march=native in the cmake which should be done for the wheels.

### CODE REVIEW

**Comment by pablospe** [comment]
Update version here too:
https://github.com/PoseLib/PoseLib/blob/567a73b766632f3c03eb6fc422f4eaac0de9e214/setup.py#L77

**Comment by pablospe** [comment]
The `PYTHON_PACKAGE` is only used here? It looks like `setup.py` and `.github/workflows/main.yml` is activating it, why? It looks like that there was some legacy code, it might be good to double check.

**Comment by pablospe** [comment]
Following issue https://github.com/PoseLib/PoseLib/issues/103. Let's create a new release after this PR. The change log could potentially be moved (or simple copy it) to the release description.

**Comment by pablospe** [comment]
> @pablospe @Parskatt it would be good to push new version to pypi as this should hopefully fix some of the crashes.

Yes, I was trying to follow up with this PR: https://github.com/PoseLib/PoseLib/pull/95.

**Review by pablospe — APPROVED** [review]

**Review by Parskatt — APPROVED** [review]
I think the least friction way is I just merge master into my fork and build the wheels from there. I might have time to do it tonight.

**Comment by Parskatt** [comment]
Wheels should now be on pypi

**Pull request merged**
